SET MY_NAME=Danny
SET SERVER_IP=127.0.0.1
SET SERVER_PORT=51235
SET MONKEY_IP=127.0.0.1
:: MonkeyInTheMiddle will use MONKEY_PORT and MONKEY_PORT+1
SET MONKEY_PORT=51233

start .\Server00.exe %SERVER_PORT%
start .\MonkeyInTheMiddle.exe %MONKEY_PORT% %SERVER_PORT% %SERVER_IP%
start .\Client00.exe 20002 %MONKEY_PORT% %MONKEY_IP% %MY_NAME%


